<?xml version="1.0" encoding="UTF-8"?>
<VPNProfile xmlns="http://www.microsoft.com/networking/VPN/vpnprofile/v1">
  <NativeProfile>
    <Servers>{{SERVER_IP}}</Servers>
    <NativeProtocolType>IKEv2</NativeProtocolType>
    <Authentication>
      <UserMethod>Eap</UserMethod>
      <Eap>
        <Configuration>
          <EapHostConfig xmlns="http://www.microsoft.com/provisioning/EapHostConfig">
            <EapMethod>
              <Type>25</Type>
              <VendorId>0</VendorId>
              <VendorType>0</VendorType>
              <AuthorId>0</AuthorId>
            </EapMethod>
            <Config xmlns="http://www.microsoft.com/provisioning/EapCommon">
              <Eap>
                <Type>25</Type>
                <EapType>
                  <ServerValidation>
                    <DisableUserPromptForServerValidation>false</DisableUserPromptForServerValidation>
                    <ServerNames>{{SERVER_SNI}}</ServerNames>
                    <TrustedRootCA>{{ROOT_CA_THUMBPRINT}}</TrustedRootCA>
                  </ServerValidation>
                  <FastReconnect>true</FastReconnect>
                  <InnerEapOptional>false</InnerEapOptional>
                  <Eap>
                    <Type>26</Type>
                    <EapType>
                      <UseWinLogonCredentials>false</UseWinLogonCredentials>
                      <CredentialsSource>
                        <CertificateStore>
                          <SimpleCertSelection>true</SimpleCertSelection>
                        </CertificateStore>
                      </CredentialsSource>
                    </EapType>
                  </Eap>
                  <EnableQuarantineChecks>false</EnableQuarantineChecks>
                  <RequireCryptoBinding>false</RequireCryptoBinding>
                  <PeapExtensions>
                    <PerformServerValidation>true</PerformServerValidation>
                    <AcceptServerName>true</AcceptServerName>
                  </PeapExtensions>
                </EapType>
              </Eap>
            </Config>
          </EapHostConfig>
        </Configuration>
      </Eap>
    </Authentication>
    <CryptographySuite>
      <AuthenticationTransformConstants>SHA256128</AuthenticationTransformConstants>
      <CipherTransformConstants>AES128</CipherTransformConstants>
      <EncryptionMethod>AES128</EncryptionMethod>
      <IntegrityCheckMethod>SHA256</IntegrityCheckMethod>
      <DHGroup>Group14</DHGroup>
      <PfsGroup>PFS2048</PfsGroup>
      <PRF>SHA256</PRF>
    </CryptographySuite>
    <RoutingPolicyType>SplitTunnel</RoutingPolicyType>
    <DisableClassBasedDefaultRoute>true</DisableClassBasedDefaultRoute>
  </NativeProfile>
  <RememberCredentials>true</RememberCredentials>
  <AlwaysOn>true</AlwaysOn>
  <TrustedNetworkDetection></TrustedNetworkDetection>
  <DeviceTunnel>false</DeviceTunnel>
  <RegisterDNS>false</RegisterDNS>
  <IPv4InterfaceMetric>1</IPv4InterfaceMetric>
  <IPv6InterfaceMetric>1</IPv6InterfaceMetric>
  <NativeProfile>
    <L2tpNativeProtocol>false</L2tpNativeProtocol>
    <SstpNativeProtocol>false</SstpNativeProtocol>
  </NativeProfile>
  <TrafficFilter>
    <AppTrigger>
      <App>
        <Id>Microsoft.MicrosoftEdge_8wekyb3d8bbwe</Id>
      </App>
    </AppTrigger>
    <RoutingPolicyType>ForceTunnel</RoutingPolicyType>
  </TrafficFilter>
  <DomainNameInformation>
    <DomainName>.corp.example.com</DomainName>
    <DomainName>example.com</DomainName>
  </DomainNameInformation>
  <DnsSuffix>example.com</DnsSuffix>
  <Proxy>
    <AutoConfigUrl>http://wpad.example.com/wpad.dat</AutoConfigUrl>
    <Manual>
      <Server>proxy.example.com:8080</Server>
      <BypassLocal>true</BypassLocal>
    </Manual>
  </Proxy>
  <Metadata>
    <Generated>{{GENERATED_DATE}}</Generated>
    <Expires>{{EXPIRY_DATE}}</Expires>
    <Username>{{USERNAME}}</Username>
    <ServerID>{{SERVER_ID}}</ServerID>
    <PSK>{{IKEV2_PSK}}</PSK>
  </Metadata>
</VPNProfile>