<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>IPSec</key>
    <dict>
        <key>AuthenticationMethod</key>
        <string>SharedSecret</string>
        <key>LocalIdentifier</key>
        <string>{{USERNAME}}</string>
        <key>RemoteAddress</key>
        <string>{{SERVER_IP}}</string>
        <key>SharedSecret</key>
        <string>{{IPSEC_PSK}}</string>
        <key>XAuthEnabled</key>
        <integer>1</integer>
        <key>XAuthName</key>
        <string>{{USERNAME}}</string>
        <key>XAuthPassword</key>
        <string>{{PASSWORD}}</string>
    </dict>
    <key>IPv4</key>
    <dict>
        <key>OverridePrimary</key>
        <integer>1</integer>
    </dict>
    <key>PPP</key>
    <dict>
        <key>AuthName</key>
        <string>{{USERNAME}}</string>
        <key>AuthPassword</key>
        <string>{{PASSWORD}}</string>
        <key>CCPEnabled</key>
        <integer>1</integer>
        <key>CCPMPPE128Enabled</key>
        <integer>1</integer>
        <key>CCPMPPE40Enabled</key>
        <integer>1</integer>
        <key>CommRemoteAddress</key>
        <string>{{SERVER_IP}}</string>
        <key>IPCPCompressionVJ</key>
        <integer>0</integer>
        <key>LCPEchoEnabled</key>
        <integer>1</integer>
        <key>LCPEchoFailure</key>
        <integer>5</integer>
        <key>LCPEchoInterval</key>
        <integer>60</integer>
    </dict>
    <key>UserDefinedName</key>
    <string>VIP-L2TP-{{USERNAME}}</string>
    <key>PayloadDescription</key>
    <string>L2TP VPN configuration for {{USERNAME}}</string>
    <key>PayloadDisplayName</key>
    <string>VIP L2TP VPN</string>
    <key>PayloadIdentifier</key>
    <string>com.vipautoscript.l2tp.{{USERNAME}}</string>
    <key>PayloadType</key>
    <string>com.apple.vpn.managed</string>
    <key>PayloadUUID</key>
    <string>{{CONFIG_UUID}}</string>
    <key>PayloadVersion</key>
    <integer>1</integer>
    <key>Proxies</key>
    <dict>
        <key>HTTPEnable</key>
        <integer>0</integer>
        <key>HTTPSEnable</key>
        <integer>0</integer>
    </dict>
    <key>VPN</key>
    <dict>
        <key>OnDemandEnabled</key>
        <integer>0</integer>
        <key>PPP</key>
        <dict>
            <key>MPPEKeySize128</key>
            <integer>1</integer>
        </dict>
        <key>PayloadCertificateUUID</key>
        <string>{{CERT_UUID}}</string>
        <key>UserDefinedName</key>
        <string>VIP-L2TP</string>
        <key>VPNType</key>
        <string>L2TP</string>
    </dict>
    <key>Metadata</key>
    <dict>
        <key>Generated</key>
        <string>{{GENERATED_DATE}}</string>
        <key>Expires</key>
        <string>{{EXPIRY_DATE}}</string>
        <key>ServerID</key>
        <string>{{SERVER_ID}}</string>
    </dict>
</dict>
</plist>l2tp.tpl