# SoftEther VPN Client Configuration
# Generated: {{GENERATED_DATE}}
# Expires: {{EXPIRY_DATE}}
declare root
{
    bool DisableUdpAcceleration false
    bool EnableSoftEtherAnalyzer false
    string AssignedDefaultGateway 0.0.0.0
    string AssignedDefaultGateway6 ::
    uint AssignedDhcpDns 0.0.0.0
    uint AssignedDhcpDns6 ::
    uint AssignedDhcpGateway 0.0.0.0
    uint AssignedDhcpGateway6 ::
    string AssignedDhcpNetwork 0.0.0.0
    string AssignedDhcpNetwork6 ::
    uint AssignedDhcpSubnet 0
    uint AssignedDhcpSubnet6 0
    string AssignedDns 0.0.0.0
    string AssignedDns6 ::
    string AssignedIp 0.0.0.0
    string AssignedIp6 ::
    uint AssignedSubnet 0
    uint AssignedSubnet6 0
    string ComputerName {{CLIENT_HOSTNAME}}
    string ConnectedTime "{{GENERATED_DATE}}"
    string ConnectionName VIP-SoftEther-{{USERNAME}}
    uint ConnectionStartedTime 0
    string ConnectionType RemoteBridge
    string CustomHeader ""
    bool DisableQoS false
    bool EnableDhcpQueue false
    bool EnableDosProtection false
    bool EnableHttpProc false
    bool EnableUdpRecovery false
    bool EnableWin7Mode false
    string ExternalProxyHostName ""
    uint ExternalProxyPort 0
    string ExternalProxyUsername ""
    string Hostname {{SERVER_IP}}
    uint HubPort 443
    string HubName VPN
    string DeviceName VPN
    string Ip 0.0.0.0
    string Ip6 ::
    bool IsBridge false
    bool IsRouter false
    bool IsSecureNAT false
    uint LastErrorCode 0
    string MacAddress ""
    uint MaxConnection 1
    uint Mtu 1500
    string Password {{PASSWORD}}
    string PlainPassword {{PASSWORD}}
    uint PortUdp 0
    uint Priority 0
    string ProxyHostName ""
    uint ProxyPort 0
    string ProxyUsername ""
    bool RequireBridgeRoutingMode false
    bool RequireMonitorMode false
    bool RetryOnServerCert false
    string SecureNATHostname 0.0.0.0
    uint SecureNATMaxSessions 128
    uint SecureNATNumDns 0
    uint SecureNATNumDhcp 0
    bool SecureNATOptionDetectDns false
    bool SecureNATOptionDetectDns6 false
    bool SecureNATOptionEnableDhcp false
    bool SecureNATOptionEnableDns false
    bool SecureNATOptionEnableNat false
    string SecureNATSubnet 0.0.0.0
    uint SecureNATSubnetMask 0
    string ServerCertHash {{SERVER_CERT_HASH}}
    bool ServerCertHashCheck false
    string ServerName {{SERVER_SNI}}
    bool UseCompress false
    bool UseEncrypt true
    string Username {{USERNAME}}
    bool UseUdpAcceleration true
    bool UseUnixDev false
}