<?xml version="1.0" encoding="UTF-8"?>
<VPNProfile xmlns="http://www.microsoft.com/networking/VPN/vpnprofile/v1">
  <NativeProfile>
    <Servers>{{SERVER_IP}}</Servers>
    <NativeProtocolType>SSTP</NativeProtocolType>
    <Authentication>
      <UserMethod>Eap</UserMethod>
      <Eap>
        <Configuration>
          <EapHostConfig xmlns="http://www.microsoft.com/provisioning/EapHostConfig">
            <EapMethod>
              <Type>25</Type>
              <VendorId>0</VendorId>
              <VendorType>0</VendorType>
              <AuthorId>0</AuthorId>
            </EapMethod>
            <Config xmlns="http://www.microsoft.com/provisioning/EapCommon">
              <Eap>
                <Type>25</Type>
                <EapType>
                  <ServerValidation>
                    <DisableUserPromptForServerValidation>false</DisableUserPromptForServerValidation>
                    <ServerNames></ServerNames>
                  </ServerValidation>
                  <FastReconnect>true</FastReconnect>
                  <InnerEapOptional>false</InnerEapOptional>
                  <Eap>
                    <Type>26</Type>
                    <EapType>
                      <UseWinLogonCredentials>false</UseWinLogonCredentials>
                    </EapType>
                  </Eap>
                  <EnableQuarantineChecks>false</EnableQuarantineChecks>
                  <RequireCryptoBinding>false</RequireCryptoBinding>
                  <PeapExtensions>
                    <PerformServerValidation>true</PerformServerValidation>
                    <AcceptServerName>true</AcceptServerName>
                  </PeapExtensions>
                </EapType>
              </Eap>
            </Config>
          </EapHostConfig>
        </Configuration>
      </Eap>
    </Authentication>
    <RoutingPolicyType>SplitTunnel</RoutingPolicyType>
    <DisableClassBasedDefaultRoute>true</DisableClassBasedDefaultRoute>
  </NativeProfile>
  <RememberCredentials>true</RememberCredentials>
  <AlwaysOn>true</AlwaysOn>
  <TrustedNetworkDetection></TrustedNetworkDetection>
  <DeviceTunnel>false</DeviceTunnel>
  <RegisterDNS>false</RegisterDNS>
  <PluginProfile>
    <ServerUrlList>{{SERVER_IP}}</ServerUrlList>
    <CustomConfiguration>
      <![CDATA[
        <SSTP>
          <Auth>{{USERNAME}}:{{PASSWORD}}</Auth>
          <Server>{{SERVER_IP}}</Server>
          <Port>443</Port>
          <SSL>true</SSL>
          <VerifyCertificate>false</VerifyCertificate>
          <Cipher>ECDHE-RSA-AES256-GCM-SHA384</Cipher>
          <MTU>1400</MTU>
          <MRU>1400</MRU>
          <MPPE>true</MPPE>
          <Compression>true</Compression>
          <TLSVersion>1.2</TLSVersion>
        </SSTP>
      ]]>
    </CustomConfiguration>
  </PluginProfile>
  <Metadata>
    <Generated>{{GENERATED_DATE}}</Generated>
    <Expires>{{EXPIRY_DATE}}</Expires>
    <Username>{{USERNAME}}</Username>
    <ServerID>{{SERVER_ID}}</ServerID>
  </Metadata>
</VPNProfile>